import json

data = json.loads("[{\"id\":\"Q1\",\"question\":\"Which OOP principle bundles data and methods that operate on the data within a single unit, hiding the internal implementation details?\",\"responses\":[\"Inheritance\",\"Polymorphism\",\"Encapsulation\",\"Abstraction\"],\"correct_answer_index\":2},{\"id\":\"Q2\",\"question\":\"What OOP principle allows a new class to inherit properties and behaviors from an existing class?\",\"responses\":[\"Abstraction\",\"Polymorphism\",\"Encapsulation\",\"Inheritance\"],\"correct_answer_index\":3},{\"id\":\"Q3\",\"question\":\"Which OOP principle allows objects of different classes to be treated as objects of a common type, often demonstrated through method overriding or interface implementation?\",\"responses\":[\"Encapsulation\",\"Polymorphism\",\"Inheritance\",\"Abstraction\"],\"correct_answer_index\":1},{\"id\":\"Q4\",\"question\":\"What is the process of showing only essential features and hiding the complex implementation details from the user?\",\"responses\":[\"Inheritance\",\"Encapsulation\",\"Abstraction\",\"Polymorphism\"],\"correct_answer_index\":2},{\"id\":\"Q5\",\"question\":\"In Object-Oriented Programming, what is a blueprint for creating objects?\",\"responses\":[\"Method\",\"Object\",\"Class\",\"Attribute\"],\"correct_answer_index\":2},{\"id\":\"Q6\",\"question\":\"Which access modifier typically restricts access to members only within the same class and its derived classes?\",\"responses\":[\"Public\",\"Private\",\"Protected\",\"Internal\"],\"correct_answer_index\":2},{\"id\":\"Q7\",\"question\":\"What is the term for defining multiple methods in the same class with the same name but different parameters (number, type, or order)?\",\"responses\":[\"Method Overriding\",\"Method Overloading\",\"Method Hiding\",\"Method Invocation\"],\"correct_answer_index\":1},{\"id\":\"Q8\",\"question\":\"What is a significant benefit of using inheritance in OOP?\",\"responses\":[\"Reduced code readability\",\"Increased coupling\",\"Code reusability\",\"Elimination of polymorphism\"],\"correct_answer_index\":2},{\"id\":\"Q9\",\"question\":\"Which of the following statements is true regarding an abstract class in OOP?\",\"responses\":[\"It cannot have any concrete (implemented) methods.\",\"It can be instantiated directly.\",\"It can have both abstract and concrete methods.\",\"It must only contain static members.\"],\"correct_answer_index\":2},{\"id\":\"Q10\",\"question\":\"Which OOP principle is primarily responsible for achieving data hiding and ensuring data integrity?\",\"responses\":[\"Polymorphism\",\"Inheritance\",\"Abstraction\",\"Encapsulation\"],\"correct_answer_index\":3}]")


for q in data:
    print(f"{q['id']}: {q['question']}")
    for i, option in enumerate(q["responses"]):
        print(f"  {i}. {option}")
    print("Correct answer:", q["responses"][q["correct_answer_index"]])
    print()