// <auto-generated />
using System;
using JobHelper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobHelper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobHelper.Models.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EducationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("JobHelper.Models.Employment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Employment");
                });

            modelBuilder.Entity("JobHelper.Models.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("Hobbies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("JobHelper.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JobHelper.Models.Education", b =>
                {
                    b.HasOne("JobHelper.Models.Resume", null)
                        .WithMany("Educations")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHelper.Models.Employment", b =>
                {
                    b.HasOne("JobHelper.Models.Resume", null)
                        .WithMany("Employment")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHelper.Models.Resume", b =>
                {
                    b.HasOne("JobHelper.Models.User", null)
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("JobHelper.Models.Language", "Languages", b1 =>
                        {
                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ResumeId", "__synthesizedOrdinal");

                            b1.ToTable("Resumes");

                            b1.ToJson("Languages");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");

                            b1.OwnsOne("JobHelper.Models.Level", "Level", b2 =>
                                {
                                    b2.Property<Guid>("LanguageResumeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Language__synthesizedOrdinal")
                                        .HasColumnType("int");

                                    b2.Property<string>("Description")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int");

                                    b2.HasKey("LanguageResumeId", "Language__synthesizedOrdinal");

                                    b2.ToTable("Resumes");

                                    b2.WithOwner()
                                        .HasForeignKey("LanguageResumeId", "Language__synthesizedOrdinal");
                                });

                            b1.Navigation("Level")
                                .IsRequired();
                        });

                    b.OwnsOne("JobHelper.Models.PersonalDetails", "PersonalDetails", b1 =>
                        {
                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CivilStatus")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateOnly?>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("DesiredJobPosition")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DriverLicense")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Gender")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LinkedIn")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nationality")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Website")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ResumeId");

                            b1.ToTable("Resumes");

                            b1.ToJson("PersonalDetails");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");

                            b1.OwnsMany("JobHelper.Models.CustomField", "CustomFields", b2 =>
                                {
                                    b2.Property<Guid>("PersonalDetailsResumeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    b2.Property<string>("Label")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PersonalDetailsResumeId", "__synthesizedOrdinal");

                                    b2.ToTable("Resumes");

                                    b2.WithOwner()
                                        .HasForeignKey("PersonalDetailsResumeId");
                                });

                            b1.Navigation("CustomFields");
                        });

                    b.OwnsMany("JobHelper.Models.Skill", "Skills", b1 =>
                        {
                            b1.Property<Guid>("ResumeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ResumeId", "__synthesizedOrdinal");

                            b1.ToTable("Resumes");

                            b1.ToJson("Skills");

                            b1.WithOwner()
                                .HasForeignKey("ResumeId");

                            b1.OwnsOne("JobHelper.Models.Level", "Level", b2 =>
                                {
                                    b2.Property<Guid>("SkillResumeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Skill__synthesizedOrdinal")
                                        .HasColumnType("int");

                                    b2.Property<string>("Description")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int");

                                    b2.HasKey("SkillResumeId", "Skill__synthesizedOrdinal");

                                    b2.ToTable("Resumes");

                                    b2.WithOwner()
                                        .HasForeignKey("SkillResumeId", "Skill__synthesizedOrdinal");
                                });

                            b1.Navigation("Level")
                                .IsRequired();
                        });

                    b.Navigation("Languages");

                    b.Navigation("PersonalDetails")
                        .IsRequired();

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("JobHelper.Models.Resume", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Employment");
                });

            modelBuilder.Entity("JobHelper.Models.User", b =>
                {
                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
